clean pipeline
Signed-off-by: AndyZiYe <yeziyu@starrocks.com>

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -357,58 +357,120 @@ jobs:
           rm -rf ${{ github.workspace }}
           mkdir -p ${{ github.workspace }}
 
-      - uses: dorny/paths-filter@v2
-        id: java-file
-        name: JAVA FILE
-        with:
-          filters: |
-            java:
-              - '**.java'
+#      - uses: dorny/paths-filter@v2
+#        id: java-file
+#        name: JAVA FILE
+#        with:
+#          filters: |
+#            java:
+#              - '**.java'
+#
+#      - run: echo ${{ steps.java-file.outputs.java }}
+#
+#      - name: BRANCH INFO
+#        id: branch
+#        run: |
+#          echo ${{github.base_ref}}
+#          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+#
+#      - uses: actions/checkout@v3
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Checkout PR
+#        run: |
+#          BRANCH=${{steps.branch.outputs.branch}}
+#          git config --global user.name "wanpengfei-git";
+#          git config --global user.email "wanpengfei91@163.com";
+#          git checkout $BRANCH;
+#          git pull;
+#          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
+#          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
+#          git checkout $BRANCH_NAME;
+#          git checkout -b merge_pr;
+#          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
+#
+#      - name: Copy checkstyle files
+#        if: ${{ steps.java-file.outputs.java == 'true' }}
+#        run: |
+#          cp fe/checkstyle* .
+#
+#      - name: Run java checkstyle
+#        if: ${{ steps.java-file.outputs.java == 'true' }}
+#        uses: dbelyaev/action-checkstyle@v0.7.5
+#        with:
+#          workdir: "./fe"
+#          checkstyle_config: checkstyle.xml
+#          reporter: 'github-pr-check'
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          fail_on_error: true
+#          level: error
 
-      - run: echo ${{ steps.java-file.outputs.java }}
-
-      - name: BRANCH INFO
-        id: branch
-        run: |
-          echo ${{github.base_ref}}
-          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-
+  sonarcloud-fe:
+    runs-on: ubuntu-latest
+    needs: sonarcloud-fe-checker
+    if: needs.fe-checker.outputs.output1 == 'true'
+    name: FE Sonarcloud Check
+    steps:
       - uses: actions/checkout@v3
         with:
-          fetch-depth: 0
+          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
 
-      - name: Checkout PR
-        run: |
-          BRANCH=${{steps.branch.outputs.branch}}
-          git config --global user.name "wanpengfei-git";
-          git config --global user.email "wanpengfei91@163.com";
-          git checkout $BRANCH;
-          git pull;
-          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
-          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
-          git checkout $BRANCH_NAME;
-          git checkout -b merge_pr;
-          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
-
-      - name: Copy checkstyle files
-        if: ${{ steps.java-file.outputs.java == 'true' }}
-        run: |
-          cp fe/checkstyle* .
-
-      - name: Run java checkstyle
-        if: ${{ steps.java-file.outputs.java == 'true' }}
-        uses: dbelyaev/action-checkstyle@v0.7.5
-        with:
-          workdir: "./fe"
-          checkstyle_config: checkstyle.xml
-          reporter: 'github-pr-check'
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          fail_on_error: true
-          level: error
+#      - name: Checkout PR
+#        run: |
+#          BRANCH=${{steps.branch.outputs.branch}}
+#          git config --global user.name "wanpengfei-git";
+#          git config --global user.email "wanpengfei91@163.com";
+#          git checkout $BRANCH;
+#          git pull;
+#          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
+#          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
+#          git checkout $BRANCH_NAME;
+#          git checkout -b merge_pr;
+#          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
+#
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: 11
+#          distribution: 'adopt'
+#
+#      - name: Cache SonarCloud packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.sonar/cache
+#          key: ${{ runner.os }}-sonar
+#          restore-keys: ${{ runner.os }}-sonar
+#
+#      - name: Cache Maven packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.m2
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: ${{ runner.os }}-maven
+#
+#      - name: Setup thrift
+#        uses: dodopizza/setup-thrift@v1
+#        with:
+#          version: 0.13.0
+#
+#      - name: Analyze FE
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+#          SONAR_TOKEN: f0fb4d25c03bae90c2e994c45c29c49dc86fc169 # ${{ secrets.SONAR_TOKEN }}
+#        run: |
+#          thrift --version
+#          whereis thrift
+#          export STARROCKS_HOME=${{ github.workspace }}
+#          source env.sh
+#          mkdir -p thirdparty/installed/bin/
+#          cd thirdparty/installed/bin/ && ln -s /usr/local/bin/thrift thrift
+#          cd ${{ github.workspace }}/fe
+#          mvn -B -DskipTests verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=StarRocks_starrocks -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.base=${{ github.base_ref }} -Dsonar.pullrequest.branch=${{ github.head_ref }}
 
   fe-ut:
     runs-on: [self-hosted, normal]
-    needs: fe-codestyle-check
+    needs: [fe-codestyle-check, sonarcloud-fe-checker]
     name: FE UT
     env:
       PR_NUMBER: ${{ github.event.number }}
@@ -505,7 +567,7 @@ jobs:
           rm -f ${{ steps.run_ut.outputs.RES_FILE }}
           rm -f ${{ steps.run_ut.outputs.RES_LOG }}
           rm -rf ${{ steps.run_ut.outputs.COV_DIR }}
-          rm -rf ${{ github.workspace }}/*
+#          rm -rf ${{ github.workspace }}/*
 
   build:
     runs-on: [self-hosted, normal]
@@ -594,7 +656,9 @@ jobs:
           cd ci-tool && source lib/init.sh
           repo="${{ github.repository }}"
           bucket_prefix=`echo ${repo%/*} | tr '[:upper:]' '[:lower:]'`
-          ./bin/deploy-cluster.sh -c ${CLUSTER_NAME} --output oss://${bucket_prefix}-ci-release/${{steps.branch.outputs.branch}}/Release/pr/${{needs.build.outputs.build_output_tar}}
+          tar_path="oss://${bucket_prefix}-ci-release/${{steps.branch.outputs.branch}}/Release/pr/${{needs.build.outputs.build_output_tar}}"
+          echo ${tar_path}
+          ./bin/deploy-cluster.sh -c ${CLUSTER_NAME} --output ${tar_path} --with-coverage
 
       - run: |
           echo "FE: ${{steps.deploy_sr.outputs.fe}}, BE: ${{steps.deploy_sr.outputs.be}}"
