aaa

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -127,78 +127,68 @@ jobs:
           git checkout -b merge_pr;
           git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
 
-      - name: UPDATE ECI & RUN UT
-        id: run_ut
-        shell: bash
-        timeout-minutes: 60
-        run: |
-          set -ex
-          rm -rf ./elastic-service
-          ln -s /var/lib/elastic-service ./elastic-service
-          cd elastic-service && git pull
-          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
-
-      - name: Prepare coverage files
+#      - name: UPDATE ECI & RUN UT
+#        id: run_ut
+#        shell: bash
+#        timeout-minutes: 60
+#        run: |
+#          set -ex
+#          rm -rf ./elastic-service
+#          ln -s /var/lib/elastic-service ./elastic-service
+#          cd elastic-service && git pull
+#          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
+#
+#      - name: Prepare coverage files
+#        run: |
+#          cd ${{ github.workspace }}/fe/fe-core
+#          cp -rf ${{ steps.run_ut.outputs.COV_DIR }} target/
+#
+#      - name: MERGE_COMMIT_SHA
+#        id: merge_commit_sha
+#        run: |
+#          set -x
+#          merge_commit_sha=`curl -L \
+#          -H "Accept: application/vnd.github+json" \
+#          -H "Authorization:  token ${{ secrets.GITHUB_TOKEN }}" \
+#          -H "X-GitHub-Api-Version: 2022-11-28" \
+#          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} 2>/dev/null \
+#          | jq .merge_commit_sha`
+#          merge_commit_sha=$(echo ${merge_commit_sha//\"})
+#          echo "merge_commit_sha=${merge_commit_sha}" >> $GITHUB_OUTPUT
+#
+#      - name: Upload cov with merge_commit_sha
+#        uses: codecov/codecov-action@v3
+#        with:
+#          override_branch: ${{ github.base_ref }}
+#          override_commit: ${{ steps.merge_commit_sha.outputs.merge_commit_sha }}
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
+#          dry_run: false
+#          override_pr: 21756
+#          name: main-fe-ut
+#          fail_ci_if_error: true
+#          verbose: true
+#
+#      - name: Coverage Report
+#        uses: codecov/codecov-action@v3
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
+#          dry_run: false
+#          name: fe-ut
+#          fail_ci_if_error: false
+#          verbose: true
+      - name: copy cov
         run: |
           cd ${{ github.workspace }}/fe/fe-core
-          cp -rf ${{ steps.run_ut.outputs.COV_DIR }} target/
-
-      - name: MERGE_COMMIT_SHA
-        id: merge_commit_sha
-        run: |
-          set -x
-          merge_commit_sha=`curl -L \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization:  token ${{ secrets.GITHUB_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} 2>/dev/null \
-          | jq .merge_commit_sha`
-          merge_commit_sha=$(echo ${merge_commit_sha//\"})
-          echo "merge_commit_sha=${merge_commit_sha}" >> $GITHUB_OUTPUT
-
-      - name: Upload cov with merge_commit_sha
-        uses: codecov/codecov-action@v3
-        with:
-          override_branch: ${{ github.base_ref }}
-          override_commit: ${{ steps.merge_commit_sha.outputs.merge_commit_sha }}
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
-          dry_run: false
-          override_pr: 21756
-          name: main-fe-ut
-          fail_ci_if_error: true
-          verbose: true
-
-      #      - name: BASE_COMMIT
-      #        id: base_commit
-      #        run: |
-      #          set -x
-      #          base_commit=`curl -L \
-      #          -H "Accept: application/vnd.github+json" \
-      #          -H "Authorization:  token ${{ secrets.GITHUB_TOKEN }}" \
-      #          -H "X-GitHub-Api-Version: 2022-11-28" \
-      #          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} 2>/dev/null \
-      #          | jq .base.sha`
-      #          base_commit=$(echo ${base_commit//\"})
-      #          echo "base_commit=${base_commit}" >> $GITHUB_OUTPUT
-      #          commit_parent: ${{ steps.base_commit.outputs.base_commit }}
-
-      - name: Coverage Report
-        uses: codecov/codecov-action@v3
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
-          dry_run: false
-          name: fe-ut
-          fail_ci_if_error: false
-          verbose: true
+          cp -rf /var/local/env/eci-t4n5cemddizibjpl3hrf_fe_ut_cov_dir/ target/
 
       - name: Patch Coverage
         run: |
           set -ex
           rm -rf ./coverchecker
           ln -s /var/local/env/coverchecker ./coverchecker
-          cd $WORKSPACE/coverchecker
+          cd ${{ github.workspace }}/coverchecker
           time_count=0
           pull_status=1
           while (( $pull_status != 0 ));do
