test

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -142,52 +142,52 @@ jobs:
           git checkout -b merge_pr;
           git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
 
+#      - name: copy cov
+#        run: |
+#          cd ${{ github.workspace }}/fe/fe-core
+#          cp -rf /var/local/env/eci-t4nbtjge2ftgkrgqzwtv_fe_ut_cov_dir/ target/
+
+      - name: UPDATE ECI & RUN UT
+        id: run_ut
+        shell: bash
+        timeout-minutes: 60
+        run: |
+          set -ex
+          rm -rf ./elastic-service
+          ln -s /var/lib/elastic-service ./elastic-service
+          cd elastic-service && git pull
+          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
+
+      - name: Clean ECI
+        if: always()
+        run: |
+          echo ${{ steps.run_ut.outputs.ECI_ID }}
+          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
+
+      - run: echo ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
+
       - name: copy cov
         run: |
           cd ${{ github.workspace }}/fe/fe-core 
-          cp -rf /var/local/env/eci-t4nbtjge2ftgkrgqzwtv_fe_ut_cov_dir/ target/
-
-#      - name: UPDATE ECI & RUN UT
-#        id: run_ut
-#        shell: bash
-#        timeout-minutes: 60
-#        run: |
-#          set -ex
-#          rm -rf ./elastic-service
-#          ln -s /var/lib/elastic-service ./elastic-service
-#          cd elastic-service && git pull
-#          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
-#
-#      - name: Clean ECI
-#        if: always()
-#        run: |
-#          echo ${{ steps.run_ut.outputs.ECI_ID }}
-#          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
-#
-#      - run: echo ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
-#
-#      - uses: codecov/codecov-action@v3
-#        with:
-#          token: ${{ secrets.CODECOV_TOKEN }}
-#          files: ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
-#          dry_run: false
-#          name: codecov-umbrella
-#          fail_ci_if_error: true
-#          verbose: true
+          cp -rf ${{ steps.run_ut.outputs.COV_DIR }} target/
 
       - uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          files: ${{ github.workspace }}/fe/fe-core/target/eci-t4nbtjge2ftgkrgqzwtv_coverage.xml
+          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
           dry_run: false
           name: codecov-umbrella
           fail_ci_if_error: true
           verbose: true
 
-#      - name: Coveralls
-#        uses: coverallsapp/github-action@v1
+#      - uses: codecov/codecov-action@v3
 #        with:
-#          path-to-lcov: /var/local/env/eci-t4nhw6wq9vt2ml650sza_fe_ut_cov_dir/coverage.xml
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: ${{ github.workspace }}/fe/fe-core/target/eci-t4nbtjge2ftgkrgqzwtv_coverage.xml
+#          dry_run: false
+#          name: codecov-umbrella
+#          fail_ci_if_error: true
+#          verbose: true
 
       - name: Clean ENV
         if: always()
