test

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -35,124 +35,110 @@ jobs:
     outputs:
       output1: ${{ steps.doc-changes-info.outputs.doc }}
     steps:
-      #      - uses: dorny/paths-filter@v2
-      #        id: changes
-      #        with:
-      #          filters: |
-      #            doc:
-      #            - 'docs/**'
-      #      - name: DOC CHECK INFO
-      #        id: doc-changes-info
-      #        run: |
-      #          echo "doc=${{ steps.changes.outputs.doc }}" >> $GITHUB_OUTPUT
+      - uses: dorny/paths-filter@v2
+        id: changes
+        with:
+          filters: |
+            doc:
+            - 'docs/**'
+      - name: DOC CHECK INFO
+        id: doc-changes-info
+        run: |
+          echo "doc=${{ steps.changes.outputs.doc }}" >> $GITHUB_OUTPUT
 
-      - run: |
+  be-checker:
+    runs-on: ubuntu-latest
+    name: BE FILTER
+    outputs:
+      output1: ${{ steps.be-changes-info.outputs.be }}
+    steps:
+      - uses: dorny/paths-filter@v2
+        id: changes
+        with:
+          filters: |
+            be:
+            - 'be/**'
+            - 'gensrc/**'
+            - 'run-be-ut.sh'
+            - 'build.sh'
+
+      - name: BE CHECK INFO
+        id: be-changes-info
+        run: |
+          echo "be=${{ steps.changes.outputs.be }}" >> $GITHUB_OUTPUT
+
+  be-ut:
+    runs-on: self-hosted
+    needs: [ be-checker ]
+    timeout-minutes: 90
+    name: BE UT
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+    steps:
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
+
+  fe-checker:
+    runs-on: ubuntu-latest
+    name: FE FILTER
+    outputs:
+      output1: ${{ steps.fe-changes-info.outputs.fe }}
+    steps:
+      - uses: dorny/paths-filter@v2
+        id: changes
+        with:
+          filters: |
+            fe:
+              - 'fe/**'
+              - 'gensrc/**'
+              - 'run-fe-ut.sh'
+              - 'java-extensions/**'
+              - 'build.sh'
+
+      - run: echo ${{ steps.changes.outputs.fe }}
+
+      - name: FE CHECK INFO
+        id: fe-changes-info
+        run: |
+          echo "fe=${{ steps.changes.outputs.fe }}" >> $GITHUB_OUTPUT
+
+  fe-ut:
+    runs-on: [self-hosted]
+    needs: fe-checker
+    name: FE UT
+    env:
+      PR_NUMBER: ${{ github.event.number }}
+    steps:
+      - name: clean
+        run: |
           set -x
-          echo ${{ github.event.pull_request.merge_commit_sha }}
-          merge_commit_sha=`curl -L \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization:  token ${{ secrets.GITHUB_TOKEN }}" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/andyziye/starrocks/pulls/${{ github.event.number }} 2>/dev/null \
-          | jq .merge_commit_sha`
-          merge_commit_sha=$(echo ${merge_commit_sha//\"})
-          echo "merge_commit_sha=${merge_commit_sha}" >> $GITHUB_OUTPUT
+          echo ${{ github.workspace }}
+          rm -rf ${{ github.workspace }}/*
 
+      - name: BRANCH INFO
+        id: branch
+        run: |
+          echo ${{github.base_ref}}
+          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
 
-#  be-checker:
-#    runs-on: ubuntu-latest
-#    name: BE FILTER
-#    outputs:
-#      output1: ${{ steps.be-changes-info.outputs.be }}
-#    steps:
-#      - uses: dorny/paths-filter@v2
-#        id: changes
-#        with:
-#          filters: |
-#            be:
-#            - 'be/**'
-#            - 'gensrc/**'
-#            - 'run-be-ut.sh'
-#            - 'build.sh'
-#
-#      - name: BE CHECK INFO
-#        id: be-changes-info
-#        run: |
-#          echo "be=${{ steps.changes.outputs.be }}" >> $GITHUB_OUTPUT
-#
-#  be-ut:
-#    runs-on: self-hosted
-#    needs: [ be-checker ]
-#    timeout-minutes: 90
-#    name: BE UT
-#    env:
-#      PR_NUMBER: ${{ github.event.number }}
-#    steps:
-#      - name: BRANCH INFO
-#        id: branch
-#        run: |
-#          echo ${{github.base_ref}}
-#          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-#
-#  fe-checker:
-#    runs-on: ubuntu-latest
-#    name: FE FILTER
-#    outputs:
-#      output1: ${{ steps.fe-changes-info.outputs.fe }}
-#    steps:
-#      - uses: dorny/paths-filter@v2
-#        id: changes
-#        with:
-#          filters: |
-#            fe:
-#              - 'fe/**'
-#              - 'gensrc/**'
-#              - 'run-fe-ut.sh'
-#              - 'java-extensions/**'
-#              - 'build.sh'
-#
-#      - run: echo ${{ steps.changes.outputs.fe }}
-#
-#      - name: FE CHECK INFO
-#        id: fe-changes-info
-#        run: |
-#          echo "fe=${{ steps.changes.outputs.fe }}" >> $GITHUB_OUTPUT
-#
-#  fe-ut:
-#    runs-on: [self-hosted]
-#    needs: fe-checker
-#    name: FE UT
-#    env:
-#      PR_NUMBER: ${{ github.event.number }}
-#    steps:
-#
-#      - name: clean
-#        run: |
-#          set -x
-#          echo ${{ github.workspace }}
-#          rm -rf ${{ github.workspace }}/*
-#
-#      - name: BRANCH INFO
-#        id: branch
-#        run: |
-#          echo ${{github.base_ref}}
-#          echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
-#
-#      - uses: actions/checkout@v3
-#        with:
-#          fetch-depth: 0
-#
-#      - name: Checkout PR
-#        run: |
-#          BRANCH=${{steps.branch.outputs.branch}}
-#          git checkout $BRANCH;
-#          git pull;
-#          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
-#          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
-#          git checkout $BRANCH_NAME;
-#          git checkout -b merge_pr;
-#          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
-#
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Checkout PR
+        run: |
+          BRANCH=${{steps.branch.outputs.branch}}
+          git checkout $BRANCH;
+          git pull;
+          BRANCH_NAME="${BRANCH}-${PR_NUMBER}";
+          git fetch origin pull/${PR_NUMBER}/head:${BRANCH_NAME};
+          git checkout $BRANCH_NAME;
+          git checkout -b merge_pr;
+          git merge --squash --no-edit ${BRANCH} || (echo "Merge conflict, please check." && exit -1);
+
 #      - name: UPDATE ECI & RUN UT
 #        id: run_ut
 #        shell: bash
@@ -177,29 +163,41 @@ jobs:
 #          cd ${{ github.workspace }}/fe/fe-core
 #          cp -rf ${{ steps.run_ut.outputs.COV_DIR }} target/
 #
-#      - uses: codecov/codecov-action@v3
+#      - name: Upload cov with merge_commit_sha
+#        uses: codecov/codecov-action@v3
 #        with:
 #          token: ${{ secrets.CODECOV_TOKEN }}
 #          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
 #          dry_run: false
-#          name: codecov-umbrella
+#          name: fe-ut
 #          fail_ci_if_error: true
 #          verbose: true
 #
-#
-##      - name: copy cov
-##        run: |
-##          cd ${{ github.workspace }}/fe/fe-core
-##          cp -rf /var/local/env/eci-t4n52phvssta56q8ey20_fe_ut_cov_dir/ target/
-##      - uses: codecov/codecov-action@v3
-##        with:
-##          token: ${{ secrets.CODECOV_TOKEN }}
-##          files: ${{ github.workspace }}/fe/fe-core/target/eci-t4n52phvssta56q8ey20_coverage.xml
-##          dry_run: false
-##          name: fe-ut
-##          fail_ci_if_error: true
-##          verbose: true
-#
+#      - name: Coverage Report
+#        uses: codecov/codecov-action@v3
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: ${{ github.workspace }}/fe/fe-core/target/${{ steps.run_ut.outputs.COV_FILE }}
+#          dry_run: false
+#          name: fe-ut
+#          fail_ci_if_error: true
+#          verbose: true
+
+
+      - name: copy cov
+        run: |
+          cd ${{ github.workspace }}/fe/fe-core
+          cp -rf /var/local/env/bak-eci-t4n52phvssta56q8ey20_fe_ut_cov_dir/ target/
+      - uses: codecov/codecov-action@v3
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: ${{ github.workspace }}/fe/fe-core/target/eci-t4n52phvssta56q8ey20_coverage.xml
+          commit_parent: ""
+          dry_run: false
+          name: fe-ut
+          fail_ci_if_error: true
+          verbose: true
+
 #      - name: Clean ENV
 #        if: always()
 #        run: |
