test

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -127,36 +127,42 @@ jobs:
           echo ${{github.base_ref}}
           echo "branch=${{github.base_ref}}" >> $GITHUB_OUTPUT
 
-#      - name: UPDATE ECI & RUN UT
-#        id: run_ut
-#        shell: bash
-#        timeout-minutes: 60
-#        run: |
-#          set -ex
-#          rm -rf ./elastic-service
-#          ln -s /var/lib/elastic-service ./elastic-service
-#          cd elastic-service && git pull
-#          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
+      - name: UPDATE ECI & RUN UT
+        id: run_ut
+        shell: bash
+        timeout-minutes: 60
+        run: |
+          set -ex
+          rm -rf ./elastic-service
+          ln -s /var/lib/elastic-service ./elastic-service
+          cd elastic-service && git pull
+          ./bin/elastic-ut.sh --pr ${PR_NUMBER} --module fe --branch ${{steps.branch.outputs.branch}}
 
-#      - run: echo ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
+      - name: Clean ECI
+        if: always()
+        run: |
+          echo ${{ steps.run_ut.outputs.ECI_ID }}
+          eci rm ${{ steps.run_ut.outputs.ECI_ID }}
 
-#      - uses: codecov/codecov-action@v3
-#        with:
-#          token: ${{ secrets.CODECOV_TOKEN }}
-#          files: ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
-#          dry_run: false
-#          name: codecov-umbrella
-#          fail_ci_if_error: true
-#          verbose: true
+      - run: echo ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
 
       - uses: codecov/codecov-action@v3
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          files: /var/local/env/eci-t4nhw6wq9vt2ml650sza_fe_ut_cov_dir/coverage.xml
+          files: ${{ steps.run_ut.outputs.COV_DIR }}/${{ steps.run_ut.outputs.COV_FILE }}
           dry_run: false
           name: codecov-umbrella
           fail_ci_if_error: true
           verbose: true
+
+#      - uses: codecov/codecov-action@v3
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: /var/local/env/eci-t4nhw6wq9vt2ml650sza_fe_ut_cov_dir/coverage.xml
+#          dry_run: false
+#          name: codecov-umbrella
+#          fail_ci_if_error: true
+#          verbose: true
 
       - name: Clean ENV
         if: always()
